### ISSUE TITLE
Unable to clone repository

### ISSUE THREAD

**Issue by iptelephony** [nucleus-js/seaduk#10]
Hi,
I'm trying to clone the repository using the instructions from `README`

```
git clone --recursive https://github.com/creationix/nucleus.git
```

I get a permission error when it tries to clone the `seaduk` directory.

```
Cloning into 'nucleus'...
remote: Counting objects: 777, done.
remote: Total 777 (delta 0), reused 0 (delta 0), pack-reused 777
Receiving objects: 100% (777/777), 198.95 KiB | 57.00 KiB/s, done.
Resolving deltas: 100% (379/379), done.
Checking connectivity... done.
Submodule 'implementations/seaduk' (git@github.com:nucleus-js/seaduk.git) registered for path 'implementations/seaduk'
Cloning into '/tmp/nucleus/implementations/seaduk'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:nucleus-js/seaduk.git' into submodule path '/tmp/nucleus/implementations/seaduk' failed
```

Any help is appreciated.

Thanks

Leo

**Comment by prust** [comment]
@iptelephony: I think I ran into the same problem & ended up just manually `git clone`ing the sub-repository into the correct folder, via `git clone https://github.com/nucleus-js/seaduk.git`.

Maybe if the git submodule config was changed to `https://github.com/nucleus-js/seaduk.git` instead of `git@github.com:nucleus-js/seaduk.git`, then a recursive git clone would work?

**Comment by iptelephony** [comment]
Thanks @prust , I ended up do exactly as you suggested.

**Comment by creationix** [comment]
I fixed the submodule link to not need github auth by default.  This should help. https://github.com/nucleus-js/design/commit/081bb61e7c95aeb74a7cb5e97d9865540bec75bc
